version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-bot
    restart: "on-failure"
    command: ["./bot"]
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./configs:/app/configs
      - .env:/app/.env
      - ./logs:/app/logs
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grpc-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-api
    restart: "on-failure"
    command: ["./api"]
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./configs:/app/configs
      - .env:/app/.env
      - ./logs:/app/logs
      - ./data:/app/data
      - ./certs:/app/certs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
